name: 'gyp_sales_analytics'
version: '1.0.0'
config-version: 2

profile: 'gyp_sales_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  gyp_sales_analytics:
    +materialized: table
    staging:
      +schema: staging
    marts:
      +schema: analytics
